## Used in:
## - site-src/v1alpha2/guides/simple-gateway.md
## - site-src/blog/2021/introducing-v1alpha2.md
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: HTTPRoute
metadata:
  name: foo
spec:
  parentRefs:
  - name: prod-web
  rules:
  - backendRefs:
    - name: foo-svc
      port: 8080
