# Copyright IBM Corp. 2019, 2022
# SPDX-License-Identifier: Apache-2.0

resources:
- standard/gateway.networking.k8s.io_gatewayclasses.yaml
- standard/gateway.networking.k8s.io_gateways.yaml
- standard/gateway.networking.k8s.io_httproutes.yaml
